### ISSUE TITLE
Issues with cryptogenerator.sh

### ISSUE THREAD

**Issue by falky64** [sxiii/cryptogenerator#1]
`Please wait, compiling the project...
./cryptogenerator.sh: line 93: make: command not found
./cryptogenerator.sh: line 96: ./build/release/src/AFLMemesCoin: No such file or                          directory
Please wait, recompilation with our newly-baked genesis block...
./cryptogenerator.sh: line 101: make: command not found
Now we are ready to rock with own cryptonote crypto!
Please go to ./cryptogenerator/build/release/src location to find your binaries.
`
I am able to get to this point, but when I have completed all 7 steps I get these errors above and there is no "./build/release/src" folder. I am new to all this and have been running around with dozens of different programs trying to get this all to work on Windows 10. I am doing everything now using GitBash which also doesn't like this first command "sudo apt install git".

**Comment by sxiii** [comment]
@falky64 the script is intended to work in bash/linux. I'm not sure you can use it without fixes in windows. Maybe you could go on with cygwin or virtualbox, but this is the hard way. It's way easier to run real linux from USB flash or install it to small hard drive parition for these tasks.

P.S. I would recommend you to never work with crypto in windows or mac. 99.99% that you will loose your money at some moment (surveillance + viruses + trojan + system instability etc.)

**Comment by falky64** [comment]
I might just use an old computer and install Linux completely, better to be
safe than sorry. Do you have a tutorial on how to create a simple miner and
have it pre configured to the new coin ready to mine? Reason I ask is I
have a facebook page of just over 200k fans for Australian Rules Memes, and
trying to setup a coin for our community. I love the cryptogenerator
interface as it makes it so much easier, I'm sure I'll work it out once I
get on Linux 😊 thank you for the quick response also, much appreciated.

**Comment by sxiii** [comment]
@falky64 the script is light enough to work on any hardware so it's good idea. The compiling might take some time, on old hardware, to say, it might take 10 minutes or more.

As for simple miner, you can take any cryptonote miner and also you'll have miner compiled with the script. It should work. If you need any further help you can contact me via telegram - by the username @fakesnowden. Please also review my steemit blog as there are some useful blog posts:

https://steemit.com/@sxiii

You have a great idea of creating such a community coin! Also, think of creating tokens on BitShares platform (or you might also consider Waves), it's easier for newcomers but not so flexible as own crypto, of course. Just contact me if you need any help on that.

Thanks for your interest :)

**Comment by falky64** [comment]
I already created a token using the Ethereum platform, "
https://etherscan.io/token/0xd48e4a7f1da6008a644812d8d436117cb4e500ef" but
I'm not satisfied it's useful for anything as there is more interest in
people being able to mine the coin and being able to use the profits to buy
AFL merchandise from our online Classifieds section. Eventually I would
like to see everyone buying and selling just using our crypto coin through
our own wallet to make it so much easier. That is why I really liked
cryotogenerator and the cryptonote blockchain.

**Comment by sxiii** [comment]
Got it, @falky64. Own coin is, of course, more interesting :) Anyways take a look at BitShares tho, it's the fastest blockchain (3 seconds) and one of the most impressive (truly decentralized exchange & online wallet & more).

**Comment by falky64** [comment]
Don't they say the faster the boochchain the higher the risk of transaction
flooding? How do they avoid this obstacle without also running out of coins
that go to miners

**Comment by sxiii** [comment]
The steemit & bitshares blockchain is so fast (100k transactions at least, and more theoretically) so it's close to impossible to flood it with transactions. Also, AFAIK, there is some additional tweaks / protection from such type of DDoS flood attack. As for the miners, the BitShares network is not mined, it's POS, and all coins are already minted. The internal transactions of tokens are fast & nearly free on BitShares and 100% free on steemit/golos. Just read about Graphene if you're interested in this blockchain. @falky64
