### ISSUE TITLE
Cryptogenerator.sh sudo command not found

### ISSUE THREAD

**Issue by falky64** [sxiii/cryptogenerator#2]
`$ ./cryptogenerator.sh
./cryptogenerator.sh: line 10: sudo: command not found
Welcome to semi-automatic cryptocurrency creation script.
This is WIP (work in progress). Pre-beta version (v 0.3)
WARNING! This script checks mostly NOTHING. If you made a mistake,
fix it manually, or re-run the script.
`

**Comment by sxiii** [comment]
@falky64 seems that you don't have "sudo" command installed. Please check your distribution on how to install "sudo" command. To enter the super user mode without sudo, you could try: `su -`. Then:
* for debian-based (DEB) distros: `apt install sudo`
* In fedora or RPM-based distros, try `yum install sudo` or `dnf install sudo`
* In arch or arch-based distros, you can use `pacman -S sudo`

Good luck.

**Comment by falky64** [comment]
Awesome, will install Sudo, thank you so much, fingers crossed :-)
